version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building application
      - echo Compiling the Typescript code
      - npm run build
  post_build:
    commands:
      - echo Build completed
artifacts:
  base-directory: "."
  files:
    - "**/*"
